# Generated by Django 3.1.2 on 2020-10-04 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbase', '0003_auto_20200920_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.date(2020, 10, 4), null=True, verbose_name='Fecha de Agenda'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora',
            field=models.TimeField(default=datetime.time(12, 43, 23, 571251), verbose_name='Hora'),
        ),
    ]
