# Generated by Django 3.1.2 on 2020-10-05 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbase', '0006_auto_20201005_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='hora',
            field=models.TimeField(default=datetime.time(12, 22, 53, 550392), verbose_name='Hora'),
        ),
    ]
