# Generated by Django 3.1.2 on 2020-10-06 03:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbase', '0009_auto_20201005_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='hora',
            field=models.TimeField(default=datetime.time(22, 15, 44, 114265), verbose_name='Hora'),
        ),
    ]
