# Generated by Django 3.1.2 on 2020-10-05 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appconsulta', '0005_auto_20201004_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.date(2020, 10, 5), null=True, verbose_name='Fecha de Historia'),
        ),
        migrations.AlterField(
            model_name='historia',
            name='hora',
            field=models.TimeField(default=datetime.time(10, 36, 7, 177767), verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.date(2020, 10, 5), null=True, verbose_name='Fecha de Atencion'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='hora',
            field=models.TimeField(default=datetime.time(10, 36, 7, 175260), verbose_name='Hora'),
        ),
    ]
