# Generated by Django 3.1.2 on 2020-10-05 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appconsulta', '0006_auto_20201005_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='hora',
            field=models.TimeField(default=datetime.time(12, 22, 53, 558916), verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='hora',
            field=models.TimeField(default=datetime.time(12, 22, 53, 556417), verbose_name='Hora'),
        ),
    ]
