# Generated by Django 3.1.2 on 2020-10-05 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appconsulta', '0007_auto_20201005_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='hora',
            field=models.TimeField(default=datetime.time(12, 34, 46, 161206), verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='hora',
            field=models.TimeField(default=datetime.time(12, 34, 46, 158675), verbose_name='Hora'),
        ),
    ]
