# Generated by Django 3.1.2 on 2020-10-06 01:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appconsulta', '0008_auto_20201005_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='hora',
            field=models.TimeField(default=datetime.time(20, 28, 36, 25438), verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='hora',
            field=models.TimeField(default=datetime.time(20, 28, 36, 21428), verbose_name='Hora'),
        ),
    ]
